/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Marlon E. Zambrano Z.
 */
public class UsuariosUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form usuariosUI
     */
    public UsuariosUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        tqtCerrar = new javax.swing.JLabel();
        tqtTitulo = new javax.swing.JLabel();
        tqtNombre = new javax.swing.JLabel();
        tqtCorreo = new javax.swing.JLabel();
        tqtContrasenia = new javax.swing.JLabel();
        tqtGranja = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        ftxCorreo = new javax.swing.JFormattedTextField();
        ptxContrasenia = new javax.swing.JPasswordField();
        cbxGranja = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setIconifiable(true);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setEnabled(false);
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tqtCerrar.setBackground(new java.awt.Color(255, 255, 255));
        tqtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tqtCerrar.setText("X");
        pnlFondo.add(tqtCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 0, 30, 30));

        tqtTitulo.setBackground(new java.awt.Color(204, 204, 204));
        tqtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tqtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tqtTitulo.setText("Gestionar Usuarios");
        pnlFondo.add(tqtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        tqtNombre.setText("Nombre :");
        pnlFondo.add(tqtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        tqtCorreo.setText("Correo :");
        pnlFondo.add(tqtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        tqtContrasenia.setText("Contrasenia :");
        pnlFondo.add(tqtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        tqtGranja.setText("Granja :");
        pnlFondo.add(tqtGranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txfNombre.setText("jTextField1");
        pnlFondo.add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 290, -1));

        ftxCorreo.setText("jFormattedTextField1");
        pnlFondo.add(ftxCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 290, -1));

        ptxContrasenia.setText("jPasswordField1");
        pnlFondo.add(ptxContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 290, -1));

        cbxGranja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlFondo.add(cbxGranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 290, -1));

        btnGuardar.setText("Guardar");
        pnlFondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        btnCancelar.setText("Cancelar");
        pnlFondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     **/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxGranja;
    private javax.swing.JFormattedTextField ftxCorreo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPasswordField ptxContrasenia;
    private javax.swing.JLabel tqtCerrar;
    private javax.swing.JLabel tqtContrasenia;
    private javax.swing.JLabel tqtCorreo;
    private javax.swing.JLabel tqtGranja;
    private javax.swing.JLabel tqtNombre;
    private javax.swing.JLabel tqtTitulo;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables


}
